parameters:
  coreshop.form.type.customer.validation_groups: [coreshop]

services:
  coreshop.form.type.customer:
    class: CoreShop\Bundle\CustomerBundle\Form\Type\CustomerType
    arguments:
      - '%coreshop.model.customer.class%'
      - '%coreshop.form.type.customer.validation_groups%'
    tags:
        - { name: form.type }
